### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: stream is closed

### ISSUE THREAD

**Issue by Peter-717** [ra1u/redis-dart#16] opened 2019-12-13 16:16 UTC
First of all, thank you so much for your library! We are using your redis-dart in our project.

Everything works well for us except the close() on a redisconnection. It throws on the console: "[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: stream is closed", despite a try and catch in our call (see snippet below where _redisConnection is the "single" instance of RedisConnection())

  Future<bool> closeRedisConnection() async {
    bool _close;

    try {
      await _redisConnection.close();
      _close = true;
    } catch (onError) {
      print('Redis Close Error: $onError');
    }
    return _close ?? false;
  }

**Comment by ra1u** [comment] 2019-12-14 16:31
Thank You for your input.

Seems to be connected with #15  and I have to admit that I was not able to make much of an progress since.  I will try to take another look and I hope to move this issue forward.

**Comment by ra1u** [comment] 2019-12-14 17:58
@Peter-717  are you able to write code in way to be included in test and to reproduce bug. You can  publish code here in this thread or other way you find appropriate. That would be valuable in better understanding of Your particular issue and might additionally benefit other users.

Kind regards, Luka

**Comment by Peter-717** [comment] 2019-12-16 21:15
Hi Luka,
Here is the code. This is basically the Flutter starter app. The Floating button calls the .close() that generates the issue.

I am using a local Redis Server. And I am subscribing to the 'test' channel. When I publish any message on that channel, it will be displayed in the app.

Let me know if I can be of any further assistance. Thanks!

Note: One more thing, how can test that the connection is still alive with the server, as in PubSub mode, we can no longer send a PING command. Thanks


import 'dart:async';
import 'package:flutter/material.dart';
import 'package:redis/redis.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Pub Sub Redis'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>{
  String messageRedis;
  String now;
  Command _command;
  Stream stream;
  StreamSubscription subscription;
  RedisConnection _redisConnection = new RedisConnection();
  PubSub pubSub;


  Future<void> finish() async {
    pubSub.unsubscribe(['']);
    await subscription.cancel();

    try {
      await _redisConnection.close();
    } on HandleUncaughtErrorHandler catch(e) {
      print('HandleUncaught: $e');
    }
  }

  Future<Command> generateConnect() async {
    print('In generate connect');
    try {
      _command = await _redisConnection.connect('127.0.0.1', 6379);

    } on HandleUncaughtErrorHandler catch(e) {
      print('Generate Connect ERROR: $e');
      if (e.toString().contains('SocketException')){
        print('Caught the socket Exception');
      }
    }
    return _command;
  }

  Future<void> startRedis() async {
    try {
      Command command = await generateConnect();
      pubSub = PubSub(command);
      pubSub.subscribe(['test']);
      stream = pubSub.getStream();

      onData(dynamic value){
        setState(() {
          messageRedis = value.toString();
          now = DateTime.now().toString();
        });
      }

      subscription = stream.listen(onData);
    } on Exception catch (e) {
      print('Start Redis: $e');
    }
  }


  @override
  void initState() {
    super.initState();
    startRedis();
  }

  @override
  void dispose() {
    subscription.cancel();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              now ?? 'Nothing yet',),
            Text(messageRedis ?? 'No message yet',
              style: Theme.of(context).textTheme.display1),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {await finish();},
        tooltip: 'Increment',
        child: Icon(Icons.stop),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by idrats** [comment] 2020-05-25 10:12
I faced with practically the same error. In my case it was `Bad state: StreamSink is closed`
You can reproduce it simply making 2 calls of redis with the same key immediately

**Comment by ra1u** [comment] 2020-05-25 11:35
@idrats Thak you for report.

Can you please post short and working example of code, so that we are able to reproduce this?

**Comment by idrats** [comment] 2020-05-25 13:08
Sorry, I have figured out, that was my mistake

**Comment by ra1u** [comment] 2020-05-25 14:06
@idrats that is great :)

I am now closing this, since we did made some progress in recent release, for this thing.
If someone finds an issue, please do open new issue and if possible post code to reproduce this.

**Closed by ra1u** 2020-05-25 14:06 UTC
